- name: Deploy Application
  hosts: app
  become: true

  vars:
    image_name: mothmon14682/pms:stable
    container_name: pms
    host_port: 80
    container_port: 8080

  tasks:
    - name: Pull the latest image
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Run new container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        recreate: true
        pull: true
        restart_policy: always
        ports:
          - "{{ host_port }}:{{ container_port }}"
        env:
          pms_db_host: "{{ pms_db_host }}"
          pms_db_name: "{{ pms_db_name }}"
          pms_db_username: "{{ pms_db_username }}"
          pms_db_password: "{{ pms_db_password }}"
      when: lookup('env','BRANCH_NAME') == 'main'
