- name: Rollback Application
  hosts: app
  become: true

  vars:
    image_repo: mothmon14682/pms
    container_name_old: pms
    container_name_new: pms_rollback
    container_port: 8080
    nginx_container_name: proxy
    nginx_config_host: /home/app-server/nginx.conf
    nginx_config_remote: /etc/nginx/nginx.conf

  tasks:
    - name: Validate image_tag is provided
      ansible.builtin.fail:
        msg: "Biến image_tag chưa được truyền vào."
      when: image_tag is not defined or image_tag == ""

    - name: Pull image version rollback
      community.docker.docker_image:
        name: "{{ image_repo }}:{{ image_tag }}"
        source: pull
        force_source: true

    - name: Chạy container rollback
      community.docker.docker_container:
        name: "{{ container_name_new }}"
        image: "{{ image_repo }}:{{ image_tag }}"
        state: started
        restart_policy: always
        networks:
          - name: pms
        env:
          db_host: "{{ db_host }}"
          db_name: "{{ db_name }}"
          db_username: "{{ db_username }}"
          db_password: "{{ db_password }}"

    - name: Chờ container rollback sẵn sàng
      community.docker.docker_container_info:
        name: "{{ container_name_new }}"
      register: container_info
      until: container_info.container.State.Running == true
      retries: 10
      delay: 3

    - name: Đổi upstream sang container rollback
      ansible.builtin.replace:
        path: "{{ nginx_config_host }}"
        regexp: 'server\s+[^;]+:{{ container_port }};'
        replace: 'server {{ container_name_new }}:{{ container_port }};'

    - name: Test Nginx config
      ansible.builtin.command: >
        docker exec {{ nginx_container_name }} nginx -t

    - name: Reload Nginx
      ansible.builtin.command: >
        docker exec {{ nginx_container_name }} nginx -s reload

    - name: Stop container cũ
      community.docker.docker_container:
        name: "{{ container_name_old }}"
        state: stopped