- name: Rollback Application
  hosts: app
  become: true

  vars:
    image_repo: mothmon14682/pms
    container_name_old: pms
    container_name_new: pms_rollback
    container_port: 8080
    nginx_container_name: proxy
    nginx_config_local: ~/nginx.conf
    nginx_config_remote: /etc/nginx/nginx.conf

  tasks:
    - name: Validate image_tag is provided
      ansible.builtin.fail:
        msg: "Biến image_tag chưa được truyền vào."
      when: image_tag is not defined or image_tag == ""

    - name: Pull image version rollback
      community.docker.docker_image:
        name: "{{ image_repo }}:{{ image_tag }}"
        source: pull
        force_source: true

    - name: Chạy container rollback
      community.docker.docker_container:
        name: "{{ container_name_new }}"
        image: "{{ image_repo }}:{{ image_tag }}"
        state: started
        restart_policy: always
        networks:
          - name: pms
        env:
          pms_db_host: "{{ db_host }}"
          pms_db_name: "{{ db_name }}"
          pms_db_username: "{{ db_username }}"
          pms_db_password: "{{ db_password }}"

    - name: Copy nginx.conf từ container ra host
      ansible.builtin.command: >
        docker cp {{ nginx_container_name }}:{{ nginx_config_remote }} {{ nginx_config_local }}

    - name: Đổi upstream sang container rollback
      ansible.builtin.replace:
        path: "{{ nginx_config_local }}"
        regexp: 'server \S+:{{ container_port }};'
        replace: 'server {{ container_name_new }}:{{ container_port }};'

    - name: Copy nginx.conf đã sửa vào container
      ansible.builtin.command: >
        docker cp {{ nginx_config_local }} {{ nginx_container_name }}:{{ nginx_config_remote }}

    - name: Reload Nginx trong container
      ansible.builtin.command: >
        docker exec {{ nginx_container_name }} nginx -s reload

    - name: Stop container cũ
      community.docker.docker_container:
        name: "{{ container_name_old }}"
        state: stopped